"""Updated Post model with title and tag

Revision ID: 70870d48c98c
Revises: 86bc964781ef
Create Date: 2024-08-02 15:21:09.487200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70870d48c98c'
down_revision = '86bc964781ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('tag', sa.String(length=64), nullable=False))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.drop_column('tag')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
