"""UpAdded Resume

Revision ID: 86bc964781ef
Revises: e443218fc62e
Create Date: 2024-08-01 21:29:05.457027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86bc964781ef'
down_revision = 'e443218fc62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('education', sa.Text(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('languages', sa.Text(), nullable=False),
    sa.Column('projects', sa.Text(), nullable=False),
    sa.Column('experience', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone_num', sa.Text(), nullable=True),
    sa.Column('linkedin', sa.Text(), nullable=False),
    sa.Column('github', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume')
    # ### end Alembic commands ###
